#ifndef _VARS_H
#define _VARS_H

// main parameters
extern char** D_52a6;   // envp
extern char** D_52a4;  // argv
extern int D_52a2;     // argc

extern int D_52ba; // force cga
extern int D_52ef; // force ega
extern int D_52f1; // force tandy
extern int D_52f3; // force herc

extern u16 D_538c;

extern u16 D_5394;
extern u16 D_5396;

extern u8  D_5893;  // map_id
extern u8  D_5895;

extern u16 D_a9bd;
extern u16 D_a9be;
extern u16 D_a9c2;
extern u8  D_a9c8;
extern u8  D_a9c9;
extern u8  D_a9ca;
extern u8  D_a9cb;
extern u8  D_a9cd;

extern u16 D_b11c;

#endif
